services:
  - type: web
    name: agrizen-backend
    runtime: docker
    plan: free
    region: singapore
    branch: main
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/agrizen-backend-0.0.1-SNAPSHOT.jar
    healthCheckPath: /actuator/health
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: agrizen-postgres
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: agrizen-postgres
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: agrizen-postgres
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: false
      - key: SPRING_JPA_HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: APP_UPLOAD_DIR
        value: /opt/render/project/src/uploads
      - key: APP_UPLOAD_BASE_URL
        value: /uploads

databases:
  - name: agrizen-postgres
    databaseName: agrigrow
    user: agrizen_user
    plan: free
    region: singapore